name: Deployment status

on: page_build

jobs:
  check-status:
    if: github.event.build.status == 'built'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main branch
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Check event
      run: echo Finally