name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
    paths: data/*
  workflow_dispatch:
  

jobs:
  sync-pages:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main branch
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Checkout gh-pages branch
      run: git checkout gh-pages

    - name: Sync data folder (overwrite existing files)
      run: |
        rm -rf data
        git checkout main -- data scripts .github/workflows/verify-pages.yml

    - name: Commit and push if changes are detected
      id: commit-step
      run: |
        echo "Changes detected in gh-pages branch."
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add data
        git add .github/workflows/verify-pages.yml
        git commit -m "Update data file(s)"
        git push
  