name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
    paths: data/*
  workflow_dispatch:
  

jobs:
  sync-pages:
    runs-on: ubuntu-latest
    outputs:
      has_changes: ${{ steps.commit-step.outputs.has_changes }}
    steps:
    - name: Checkout main branch
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Checkout gh-pages branch
      run: git checkout gh-pages

    - name: Copy new files to data folder (overwrite existing files)
      run: |
        git checkout main -- data scripts

    - name: Commit and push if changes are detected
      id: commit-step
      run: |
        if [ -n "$(git status data --porcelain)" ]; then
          echo "Changes detected in gh-pages branch."
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add data
          git commit -m "Update data file(s)"
          git push

          echo "has_changes=true" >> $GITHUB_OUTPUT
          
        else
          echo "No changes to commit and push."
          echo "has_changes=false" >> $GITHUB_OUTPUT
        fi
  verify-pages:
    needs: sync-pages
    if: needs.sync-pages.outputs.has_changes == 'true'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main branch
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Verifying pages api
      run: |
        echo "Verifying pages deployment"
        node scripts/verify-pages.js ${{ secrets.GITHUB_TOKEN }} ${{ github.repository_owner }} ${{ github.repository }}
  