name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write

    steps:
    - name: Checkout main branch
      uses: actions/checkout@v1

    - name: Setup Git
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"

    - name: Checkout gh-pages branch
      run: git checkout gh-pages

    - name: Copy new files
      run: |
        cp -r data/* .

    - name: Commit and push changes
      run: |
        git add .
        git commit -m "Update gh-pages with new files"
        git push

