name: Verify pages build

on: 
  page_build

jobs:
  check-status:
    if: github.event.build.status == 'built'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main branch
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install dependencies
      run: yarn install --frozen-lockfile
    - name: Verifying pages api
      run: |
        echo "Verifying pages deployment"
        node scripts/verify-pages.js ${{ secrets.GITHUB_TOKEN }} ${{ github.repository_owner }} ${{ github.repository }}